<Project>
  <PropertyGroup>
    <AndroidNdkRevision>27.3.13750724</AndroidNdkRevision>
    <AndroidApiLevel>26</AndroidApiLevel>
    <AndroidBuildToolsRevision>36.0.0</AndroidBuildToolsRevision>
    <AndroidJavaCompilerVersion>21.0.8</AndroidJavaCompilerVersion>
    <JavaInteropRevision>5b9effb3e32df58a91257f7f92aa595679862a33</JavaInteropRevision>
    <JavaInteropRepositoryUrl>https://github.com/dotnet/android.git</JavaInteropRepositoryUrl>

    <AndroidDobbyRevision>be22f55a2adab028bb2d3264589df1cb3f1aea9f</AndroidDobbyRevision>
    <AndroidDobbyRepositoryUrl>https://github.com/LemonLoaderX/Dobby.git</AndroidDobbyRepositoryUrl>
    <AndroidIl2CppInteropVersion>1.5.3</AndroidIl2CppInteropVersion>
    <AndroidIl2CppInteropRevision>bdcf72ef046090e3236e6a9bd80b3f00f9e344f5</AndroidIl2CppInteropRevision>
    <AndroidIl2CppInteropRepositoryUrl>https://github.com/LemonLoaderX/Il2CppInterop.git</AndroidIl2CppInteropRepositoryUrl>
    <AndroidHarmonyXVersion>2.10.2</AndroidHarmonyXVersion>
    <AndroidHarmonyXRevision>e840099c922b9b4c81facd653b1daf84c978ae6a</AndroidHarmonyXRevision>
    <AndroidHarmonyXRepositoryUrl>https://github.com/LemonLoaderX/HarmonyX.git</AndroidHarmonyXRepositoryUrl>
    <AndroidMonoModVersion>22.7.31.1</AndroidMonoModVersion>
    <AndroidMonoModRevision>58743d026f2239add4116fe414d3478de205b237</AndroidMonoModRevision>
    <AndroidMonoModRepositoryUrl>https://github.com/LemonLoaderX/MonoMod.git</AndroidMonoModRepositoryUrl>
  </PropertyGroup>
</Project>
