<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier></RuntimeIdentifier>
    <RuntimeIdentifiers></RuntimeIdentifiers>
    <DefineConstants>ANDROID</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../MelonLoader/JNI/*.cs" Link="JNI/%(Filename)%(Extension)" />
    <Compile Include="../../../MelonLoader/Utils/APKAssetManager.cs" Link="APKAssetManager.cs" />
    <Compile Include="../../../MelonLoader/LoaderConfig.cs" Link="LoaderConfig.cs" />
    <Compile Include="../../../MelonLoader/NativeUtils/NativeHooks.cs" Link="NativeHooks.cs" />
    <Compile Include="../../../MelonLoader/InternalUtils/BootstrapInterop.cs" Link="BootstrapInterop.cs" />
    <Compile Include="../../../Dependencies/SupportModules/SceneHandler.cs" Link="SceneHandler.cs" />
    <PackageReference Include="Samboy063.Tomlet" Version="$(TomletVersion)" />
  </ItemGroup>
</Project>
